// Dữ liệu từ vựng
const vocabularyDataFull = [
  // 1. Đại từ & nhân xưng
  { chinese: "你", pinyin: "nǐ", meaning: "bạn", category: "1", part: "1" },
  { chinese: "我", pinyin: "wǒ", meaning: "tôi", category: "1", part: "1" },
  { chinese: "她", pinyin: "tā", meaning: "cô ấy, bà ấy", category: "1", part: "1" },
  { chinese: "他", pinyin: "tā", meaning: "anh ấy, ông ấy", category: "1", part: "1" },
  { chinese: "我们", pinyin: "wǒmen", meaning: "chúng tôi, chúng ta", category: "1", part: "1" },
  { chinese: "您", pinyin: "nín", meaning: "ngài, ông, bà (kính ngữ)", category: "1", part: "1" },
  { chinese: "们", pinyin: "men", meaning: "các (hậu tố số nhiều)", category: "1", part: "1" },

  // 2. Động từ & trợ động từ
  { chinese: "是", pinyin: "shì", meaning: "là", category: "2", part: "1" },
  { chinese: "叫", pinyin: "jiào", meaning: "tên là, gọi là", category: "2", part: "1" },
  { chinese: "不", pinyin: "bù", meaning: "không", category: "2", part: "1" },
  { chinese: "说", pinyin: "shuō", meaning: "nói", category: "2", part: "1" },
  { chinese: "会", pinyin: "huì", meaning: "biết, có thể", category: "2", part: "1" },
  { chinese: "学", pinyin: "xué", meaning: "học", category: "2", part: "1" },
  { chinese: "写", pinyin: "xiě", meaning: "viết", category: "2", part: "1" },
  { chinese: "吃", pinyin: "chī", meaning: "ăn", category: "2", part: "1" },
  { chinese: "喜欢", pinyin: "xǐhuan", meaning: "thích", category: "2", part: "1" },
  { chinese: "喝", pinyin: "hē", meaning: "uống", category: "2", part: "1" },
  { chinese: "想", pinyin: "xiǎng", meaning: "muốn, nghĩ", category: "2", part: "1" },
  { chinese: "买", pinyin: "mǎi", meaning: "mua", category: "2", part: "1" },
  { chinese: "有", pinyin: "yǒu", meaning: "có", category: "2", part: "1" },
  { chinese: "没有", pinyin: "méiyǒu", meaning: "không có", category: "2", part: "1" },
  { chinese: "做", pinyin: "zuò", meaning: "làm", category: "2", part: "1" },
  { chinese: "去", pinyin: "qù", meaning: "đi", category: "2", part: "1" },
  { chinese: "回", pinyin: "huí", meaning: "về, quay lại", category: "2", part: "1" },
  { chinese: "来", pinyin: "lái", meaning: "đến", category: "2", part: "1" },
  { chinese: "看", pinyin: "kàn", meaning: "nhìn, xem", category: "2", part: "1" },
  { chinese: "看见", pinyin: "kànjiàn", meaning: "nhìn thấy", category: "2", part: "1" },
  { chinese: "没", pinyin: "méi", meaning: "không (viết tắt)", category: "2", part: "1" },
  { chinese: "住", pinyin: "zhù", meaning: "sống, ở", category: "2", part: "1" },
  { chinese: "工作", pinyin: "gōngzuò", meaning: "công việc, làm việc", category: "2", part: "1" },
  { chinese: "认识", pinyin: "rènshi", meaning: "quen biết", category: "2", part: "1" },
  { chinese: "坐", pinyin: "zuò", meaning: "ngồi, đi (bằng phương tiện)", category: "2", part: "1" },
  { chinese: "请", pinyin: "qǐng", meaning: "mời, xin", category: "2", part: "1" },
  { chinese: "到", pinyin: "dào", meaning: "đến", category: "2", part: "1" },
  { chinese: "睡觉", pinyin: "shuìjiào", meaning: "ngủ", category: "2", part: "1" },
  { chinese: "开", pinyin: "kāi", meaning: "mở, lái (xe)", category: "2", part: "1" },
  { chinese: "问", pinyin: "wèn", meaning: "hỏi", category: "2", part: "1" },
  { chinese: "读", pinyin: "dú", meaning: "đọc", category: "2", part: "1" },
  { chinese: "爱", pinyin: "ài", meaning: "yêu", category: "2", part: "1" },
  { chinese: "听", pinyin: "tīng", meaning: "nghe", category: "2", part: "1" },
  { chinese: "打电话", pinyin: "dǎ diànhuà", meaning: "gọi điện thoại", category: "2", part: "1" },
  { chinese: "介绍", pinyin: "jièshào", meaning: "giới thiệu", category: "2", part: "1" },
  { chinese: "可以", pinyin: "kěyǐ", meaning: "có thể, được", category: "2", part: "1" },
  { chinese: "等", pinyin: "děng", meaning: "đợi", category: "2", part: "1" },
  { chinese: "要", pinyin: "yào", meaning: "cần, muốn, sắp", category: "2", part: "1" },
  { chinese: "离", pinyin: "lí", meaning: "cách, rời khỏi", category: "2", part: "2" },
  { chinese: "走", pinyin: "zǒu", meaning: "đi bộ", category: "2", part: "2" },
  { chinese: "往", pinyin: "wǎng", meaning: "hướng về, đi về", category: "2", part: "2" },
  { chinese: "从", pinyin: "cóng", meaning: "từ", category: "2", part: "2" },
  { chinese: "完", pinyin: "wán", meaning: "xong, hoàn thành", category: "2", part: "2" },
  { chinese: "觉得", pinyin: "juéde", meaning: "cảm thấy", category: "2", part: "2" },
  { chinese: "需要", pinyin: "xūyào", meaning: "cần", category: "2", part: "2" },
  { chinese: "帮助", pinyin: "bāngzhù", meaning: "giúp đỡ", category: "2", part: "2" },
  { chinese: "试", pinyin: "shì", meaning: "thử", category: "2", part: "2" },
  { chinese: "洗", pinyin: "xǐ", meaning: "rửa, giặt", category: "2", part: "2" },
  { chinese: "跑步", pinyin: "pǎobù", meaning: "chạy bộ", category: "2", part: "2" },
  { chinese: "踢足球", pinyin: "tī zúqiú", meaning: "đá bóng", category: "2", part: "2" },
  { chinese: "跳舞", pinyin: "tiàowǔ", meaning: "nhảy múa", category: "2", part: "2" },
  { chinese: "上课", pinyin: "shàngkè", meaning: "lên lớp, vào học", category: "2", part: "2" },
  { chinese: "游", pinyin: "yóu", meaning: "bơi", category: "2", part: "2" },
  { chinese: "游泳", pinyin: "yóuyǒng", meaning: "bơi lội", category: "2", part: "2" },
  { chinese: "给", pinyin: "gěi", meaning: "cho", category: "2", part: "2" },
  { chinese: "知道", pinyin: "zhīdào", meaning: "biết", category: "2", part: "2" },
  { chinese: "懂", pinyin: "dǒng", meaning: "hiểu", category: "2", part: "2" },
  { chinese: "唱歌", pinyin: "chànggē", meaning: "hát", category: "2", part: "2" },
  { chinese: "出", pinyin: "chū", meaning: "ra, đi ra", category: "2", part: "2" },
  { chinese: "进", pinyin: "jìn", meaning: "vào, đi vào", category: "2", part: "2" },
  { chinese: "开始", pinyin: "kāishǐ", meaning: "bắt đầu", category: "2", part: "2" },
  { chinese: "下班", pinyin: "xiàbān", meaning: "tan làm", category: "2", part: "2" },
  { chinese: "休息", pinyin: "xiūxi", meaning: "nghỉ ngơi", category: "2", part: "2" },
  { chinese: "过", pinyin: "guò", meaning: "qua, trải qua", category: "2", part: "2" },
  { chinese: "预订", pinyin: "yùdìng", meaning: "đặt trước", category: "2", part: "2" },
  { chinese: "让", pinyin: "ràng", meaning: "để, cho phép", category: "2", part: "2" },
  { chinese: "穿", pinyin: "chuān", meaning: "mặc (quần áo)", category: "2", part: "2" },
  { chinese: "旅游", pinyin: "lǚyóu", meaning: "du lịch", category: "2", part: "2" },
  { chinese: "找", pinyin: "zhǎo", meaning: "tìm, trả tiền thừa(thối tiền)", category: "2", part: "3" },
  { chinese: "玩", pinyin: "wán", meaning: "chơi", category: "2", part: "2" },
  { chinese: "关", pinyin: "guān", meaning: "đóng, tắt", category: "2", part: "2" },
  { chinese: "打篮球", pinyin: "dǎ lánqiú", meaning: "chơi bóng rổ", category: "2", part: "2" },
  { chinese: "笑", pinyin: "xiào", meaning: "cười", category: "2", part: "2" },
  { chinese: "上班", pinyin: "shàngbān", meaning: "đi làm", category: "2", part: "2" },
  { chinese: "迟到", pinyin: "chídào", meaning: "đến muộn", category: "2", part: "2" },
  { chinese: "送", pinyin: "sòng", meaning: "tặng, đưa, tiễn", category: "2", part: "2" },
  { chinese: "卖", pinyin: "mài", meaning: "bán", category: "2", part: "2" },
  { chinese: "告诉", pinyin: "gàosu", meaning: "nói, bảo, kể", category: "2", part: "2" },
  { chinese: "说话", pinyin: "shuōhuà", meaning: "nói chuyện", category: "2", part: "2" },
  { chinese: "希望", pinyin: "xīwàng", meaning: "hy vọng", category: "2", part: "2" },
  { chinese: "站", pinyin: "zhàn", meaning: "đứng, trạm(bến)", category: "2", part: "3" },
  { chinese: "接", pinyin: "jiē", meaning: "đón, nhận, tiếp", category: "2", part: "3" },
  { chinese: "起飞", pinyin: "qǐfēi", meaning: "cất cánh", category: "2", part: "3" },
  { chinese: "见", pinyin: "jiàn", meaning: "gặp, thấy", category: "2", part: "3" },
  { chinese: "考", pinyin: "kǎo", meaning: "thi, kiểm tra", category: "2", part: "3" },
  { chinese: "教", pinyin: "jiāo", meaning: "dạy", category: "2", part: "3" },
  { chinese: "复习", pinyin: "fùxí", meaning: "ôn tập", category: "2", part: "3" },
  { chinese: "放", pinyin: "fàng", meaning: "đặt, để", category: "2", part: "3" },
  { chinese: "画", pinyin: "huà", meaning: "vẽ, bức tranh", category: "2", part: "3" },
  { chinese: "带", pinyin: "dài", meaning: "mang, đai", category: "2", part: "3" },
  { chinese: "飞", pinyin: "fēi", meaning: "bay", category: "2", part: "3" },
  { chinese: "拍", pinyin: "pāi", meaning: "chụp (ảnh), vỗ", category: "2", part: "3" },
  { chinese: "遇到", pinyin: "yùdào", meaning: "gặp, gặp phải", category: "2", part: "3" },
  { chinese: "刷牙", pinyin: "shuāyá", meaning: "đánh răng", category: "2", part: "3" },
  { chinese: "洗澡", pinyin: "xǐzǎo", meaning: "tắm", category: "2", part: "3" },
  { chinese: "订", pinyin: "dìng", meaning: "đặt, đặt trước", category: "2", part: "3" },
  { chinese: "应该", pinyin: "yīnggāi", meaning: "nên, phải, có lẽ", category: "2", part: "3" },
  { chinese: "欢迎", pinyin: "huānyíng", meaning: "hoan nghênh, chào đón", category: "2", part: "3" },
  { chinese: "点", pinyin: "diǎn", meaning: "gọi (món), giờ", category: "2", part: "3" },
  { chinese: "换", pinyin: "huàn", meaning: "đổi, thay đổi", category: "2", part: "3" },
  { chinese: "习惯", pinyin: "xíguàn", meaning: "quen, thói quen", category: "2", part: "3" },
  { chinese: "打算", pinyin: "dǎsuàn", meaning: "dự định, tính toán", category: "2", part: "3" },
  { chinese: "着急", pinyin: "zháojí", meaning: "sốt ruột, lo lắng", category: "2", part: "3" },
  { chinese: "拿", pinyin: "ná", meaning: "cầm, lấy", category: "2", part: "3" },
  { chinese: "听说", pinyin: "tīngshuō", meaning: "nghe nói", category: "2", part: "3" },
  { chinese: "赚", pinyin: "zhuàn", meaning: "kiếm (tiền)", category: "2", part: "3" },
  { chinese: "结婚", pinyin: "jiéhūn", meaning: "kết hôn, cưới", category: "2", part: "3" },
  { chinese: "愿意", pinyin: "yuànyì", meaning: "đồng ý, sẵn lòng", category: "2", part: "3" },
  { chinese: "离开", pinyin: "líkāi", meaning: "rời khỏi", category: "2", part: "3" },
  { chinese: "满意", pinyin: "mǎnyì", meaning: "hài lòng", category: "2", part: "3" },
  { chinese: "用", pinyin: "yòng", meaning: "dùng, sử dụng", category: "2", part: "4" },
  { chinese: "向", pinyin: "xiàng", meaning: "hướng về, đối với", category: "2", part: "4" },
  { chinese: "疼", pinyin: "téng", meaning: "đau, nhức", category: "2", part: "4" },
  { chinese: "参加", pinyin: "cānjiā", meaning: "tham gia", category: "2", part: "4" },
  { chinese: "祝", pinyin: "zhù", meaning: "chúc", category: "2", part: "4" },
  { chinese: "租", pinyin: "zū", meaning: "thuê", category: "2", part: "4" },
  { chinese: "上网", pinyin: "shàngwǎng", meaning: "lên mạng", category: "2", part: "4" },
  { chinese: "请假", pinyin: "qǐngjià", meaning: "xin nghỉ phép", category: "2", part: "4" },
  { chinese: "生气", pinyin: "shēngqì", meaning: "tức giận", category: "2", part: "4" },
  { chinese: "发现", pinyin: "fāxiàn", meaning: "phát hiện", category: "2", part: "4" },
  { chinese: "影响", pinyin: "yǐngxiǎng", meaning: "ảnh hưởng", category: "2", part: "4" },
  { chinese: "借", pinyin: "jiè", meaning: "mượn", category: "2", part: "4" },
  { chinese: "还", pinyin: "huán", meaning: "trả lại", category: "2", part: "4" },
  { chinese: "留", pinyin: "liú", meaning: "ở lại, giữ lại", category: "2", part: "4" },
  { chinese: "锻炼", pinyin: "duànliàn", meaning: "rèn luyện", category: "2", part: "4" },
  { chinese: "注意", pinyin: "zhùyì", meaning: "chú ý", category: "2", part: "4" },
  { chinese: "减肥", pinyin: "jiǎnféi", meaning: "giảm cân", category: "2", part: "4" },
  { chinese: "骑", pinyin: "qí", meaning: "cưỡi, đi (xe đạp, ngựa)", category: "2", part: "4" },
  { chinese: "敢", pinyin: "gǎn", meaning: "dám", category: "2", part: "4" },
  { chinese: "必须", pinyin: "bìxū", meaning: "phải, nhất định phải", category: "2", part: "4" },

  // 3. Nghề nghiệp & quan hệ 
  { chinese: "学生", pinyin: "xuésheng", meaning: "học sinh", category: "3", part: "1" },
  { chinese: "工程师", pinyin: "gōngchéngshī", meaning: "kỹ sư", category: "3", part: "1" },
  { chinese: "老师", pinyin: "lǎoshī", meaning: "thầy giáo, cô giáo", category: "3", part: "1" },
  { chinese: "爸爸", pinyin: "bàba", meaning: "bố, ba", category: "3", part: "1" },
  { chinese: "妈妈", pinyin: "māma", meaning: "mẹ", category: "3", part: "1" },
  { chinese: "弟弟", pinyin: "dìdi", meaning: "em trai", category: "3", part: "1" },
  { chinese: "朋友", pinyin: "péngyǒu", meaning: "bạn bè", category: "3", part: "1" },
  { chinese: "同学", pinyin: "tóngxué", meaning: "bạn học", category: "3", part: "1" },
  { chinese: "人", pinyin: "rén", meaning: "người", category: "3", part: "1" },
  { chinese: "员工", pinyin: "yuángōng", meaning: "nhân viên", category: "3", part: "1" },
  { chinese: "职员", pinyin: "zhíyuán", meaning: "nhân viên văn phòng", category: "3", part: "1" },
  { chinese: "先生", pinyin: "xiānsheng", meaning: "ông, ngài", category: "3", part: "1" },
  { chinese: "妻子", pinyin: "qīzi", meaning: "vợ", category: "3", part: "1" },
  { chinese: "女儿", pinyin: "nǚ'ér", meaning: "con gái", category: "3", part: "1" },
  { chinese: "儿子", pinyin: "érzi", meaning: "con trai", category: "3", part: "1" },
  { chinese: "医生", pinyin: "yīshēng", meaning: "bác sĩ", category: "3", part: "1" },
  { chinese: "女孩", pinyin: "nǚhái", meaning: "cô gái, bé gái", category: "3", part: "1" },
  { chinese: "姐姐", pinyin: "jiějie", meaning: "chị gái", category: "3", part: "1" },
  { chinese: "男孩", pinyin: "nánhái", meaning: "con trai, bé trai", category: "3", part: "2" },
  { chinese: "孩子", pinyin: "háizi", meaning: "con cái, trẻ con", category: "3", part: "2" },
  { chinese: "老婆", pinyin: "lǎopo", meaning: "vợ (thông tục)", category: "3", part: "2" },
  { chinese: "老公", pinyin: "lǎogōng", meaning: "chồng (thông tục)", category: "3", part: "2" },
  { chinese: "哥哥", pinyin: "gēge", meaning: "anh trai", category: "3", part: "2" },
  { chinese: "服务员", pinyin: "fúwùyuán", meaning: "nhân viên phục vụ", category: "3", part: "2" },
  { chinese: "妹妹", pinyin: "mèimei", meaning: "em gái", category: "3", part: "2" },
  { chinese: "男", pinyin: "nán", meaning: "nam", category: "3", part: "2" },
  { chinese: "女", pinyin: "nǚ", meaning: "nữ", category: "3", part: "2" },
  { chinese: "经理", pinyin: "jīnglǐ", meaning: "quản lý, giám đốc", category: "3", part: "3" },
  { chinese: "同事", pinyin: "tóngshì", meaning: "đồng nghiệp", category: "3", part: "3" },
  { chinese: "司机", pinyin: "sījī", meaning: "tài xế, lái xe", category: "3", part: "3" },
  { chinese: "爷爷", pinyin: "yéye", meaning: "ông nội", category: "3", part: "4" },
  { chinese: "奶奶", pinyin: "nǎinai", meaning: "bà nội", category: "3", part: "4" },
  { chinese: "叔叔", pinyin: "shūshu", meaning: "chú, cậu", category: "3", part: "4" },
  { chinese: "阿姨", pinyin: "āyí", meaning: "dì, cô, bác gái", category: "3", part: "4" },
  { chinese: "运动员", pinyin: "yùndòngyuán", meaning: "vận động viên", category: "3", part: "4" },
  // 4. Quốc gia & dân tộc
  { chinese: "中国", pinyin: "zhōngguó", meaning: "Trung Quốc", category: "4", part: "1" },
  { chinese: "美国", pinyin: "měiguó", meaning: "Mỹ", category: "4", part: "1" },
  { chinese: "越南", pinyin: "yuènán", meaning: "Việt Nam", category: "4", part: "1" },

  // 5. Ngôn ngữ & chữ viết
  { chinese: "汉语", pinyin: "hànyǔ", meaning: "tiếng Hán, tiếng Trung", category: "5", part: "1" },
  { chinese: "英语", pinyin: "yīngyǔ", meaning: "tiếng Anh", category: "5", part: "1" },
  { chinese: "越南语", pinyin: "yuènányǔ", meaning: "tiếng Việt", category: "5", part: "1" },
  { chinese: "汉字", pinyin: "hànzì", meaning: "chữ Hán", category: "5", part: "1" },
  { chinese: "字", pinyin: "zì", meaning: "chữ", category: "5", part: "1" },
  { chinese: "课", pinyin: "kè", meaning: "bài học, lớp học", category: "5", part: "2" },
  { chinese: "数学", pinyin: "shùxué", meaning: "môn Toán", category: "5", part: "3" },
  { chinese: "历史", pinyin: "lìshǐ", meaning: "môn Lịch sử", category: "5", part: "3" },

  // 6. Thời gian & số đếm
  { chinese: "一", pinyin: "yī", meaning: "một", category: "6", part: "1" },
  { chinese: "二", pinyin: "èr", meaning: "hai", category: "6", part: "1" },
  { chinese: "三", pinyin: "sān", meaning: "ba", category: "6", part: "1" },
  { chinese: "四", pinyin: "sì", meaning: "bốn", category: "6", part: "1" },
  { chinese: "五", pinyin: "wǔ", meaning: "năm", category: "6", part: "1" },
  { chinese: "六", pinyin: "liù", meaning: "sáu", category: "6", part: "1" },
  { chinese: "七", pinyin: "qī", meaning: "bảy", category: "6", part: "1" },
  { chinese: "八", pinyin: "bā", meaning: "tám", category: "6", part: "1" },
  { chinese: "九", pinyin: "jiǔ", meaning: "chín", category: "6", part: "1" },
  { chinese: "十", pinyin: "shí", meaning: "mười", category: "6", part: "1" },
  { chinese: "零", pinyin: "líng", meaning: "không (số 0)", category: "6", part: "1" },
  { chinese: "百", pinyin: "bǎi", meaning: "trăm", category: "6", part: "1" },
  { chinese: "今天", pinyin: "jīntiān", meaning: "hôm nay", category: "6", part: "1" },
  { chinese: "昨天", pinyin: "zuótiān", meaning: "hôm qua", category: "6", part: "1" },
  { chinese: "明天", pinyin: "míngtiān", meaning: "ngày mai", category: "6", part: "1" },
  { chinese: "上午", pinyin: "shàngwǔ", meaning: "buổi sáng", category: "6", part: "1" },
  { chinese: "中午", pinyin: "zhōngwǔ", meaning: "buổi trưa", category: "6", part: "1" },
  { chinese: "下午", pinyin: "xiàwǔ", meaning: "buổi chiều", category: "6", part: "1" },
  { chinese: "月", pinyin: "yuè", meaning: "tháng", category: "6", part: "1" },
  { chinese: "年", pinyin: "nián", meaning: "năm", category: "6", part: "1" },
  { chinese: "岁", pinyin: "suì", meaning: "tuổi", category: "6", part: "1" },
  { chinese: "生日", pinyin: "shēngrì", meaning: "sinh nhật", category: "6", part: "1" },
  { chinese: "现在", pinyin: "xiànzài", meaning: "bây giờ", category: "6", part: "1" },
  { chinese: "分钟", pinyin: "fēnzhōng", meaning: "phút", category: "6", part: "1" },
  { chinese: "时候", pinyin: "shíhou", meaning: "thời gian, lúc", category: "6", part: "1" },
  { chinese: "时间", pinyin: "shíjiān", category: "6", meaning: "thời gian", part: "1" },
  { chinese: "多久", pinyin: "duōjiǔ", meaning: "bao lâu", category: "6", part: "1" },
  { chinese: "小时", pinyin: "xiǎoshí", meaning: "tiếng đồng hồ", category: "6", part: "1" },
  { chinese: "两", pinyin: "liǎng", meaning: "hai, đôi", category: "6", part: "2" },
  { chinese: "早上", pinyin: "zǎoshang", meaning: "buổi sáng sớm", category: "6", part: "2" },
  { chinese: "日", pinyin: "rì", meaning: "ngày", category: "6", part: "2" },
  { chinese: "千", pinyin: "qiān", meaning: "nghìn", category: "6", part: "2" },
  { chinese: "万", pinyin: "wàn", meaning: "vạn, mười nghìn", category: "6", part: "2" },
  { chinese: "次", pinyin: "cì", meaning: "lần", category: "6", part: "2" },
  { chinese: "分", pinyin: "fēn", meaning: "phút, điểm số, phân chia", category: "6", part: "4" },
  { chinese: "春天", pinyin: "chūntiān", meaning: "mùa xuân", category: "6", part: "3" },
  { chinese: "夏天", pinyin: "xiàtiān", meaning: "mùa hè", category: "6", part: "3" },
  { chinese: "秋天", pinyin: "qiūtiān", meaning: "mùa thu", category: "6", part: "3" },
  { chinese: "冬天", pinyin: "dōngtiān", meaning: "mùa đông", category: "6", part: "3" },
  { chinese: "半", pinyin: "bàn", meaning: "nửa, rưỡi", category: "6", part: "3" },
  { chinese: "刻", pinyin: "kè", meaning: "khắc, 15 phút", category: "6", part: "3" },
  { chinese: "以后", pinyin: "yǐhòu", meaning: "sau này, sau đó", category: "6", part: "3" },
  { chinese: "以前", pinyin: "yǐqián", meaning: "trước đây, trước kia", category: "6", part: "3" },
  { chinese: "元", pinyin: "yuán", meaning: "đồng (đơn vị tiền tệ)", category: "6", part: "3" },
  { chinese: "角", pinyin: "jiǎo", meaning: "hào (0.1 tệ)", category: "6", part: "3" },
  { chinese: "一共", pinyin: "yígòng", meaning: "tổng cộng", category: "6", part: "3" },
  { chinese: "季节", pinyin: "jìjié", meaning: "mùa", category: "6", part: "3" },
  { chinese: "周末", pinyin: "zhōumò", meaning: "cuối tuần", category: "6", part: "3" },
  { chinese: "公里", pinyin: "gōnglǐ", meaning: "kilômét (km)", category: "6", part: "4" },
  { chinese: "层", pinyin: "céng", meaning: "tầng (lầu)", category: "6", part: "4" },
  { chinese: "后来", pinyin: "hòulái", meaning: "sau này, sau đó", category: "6", part: "4" },
  { chinese: "一直", pinyin: "yìzhí", meaning: "luôn luôn, mãi", category: "6", part: "4" },

  // 7. Thức ăn & đồ uống
  { chinese: "饭", pinyin: "fàn", meaning: "cơm", category: "7", part: "1" },
  { chinese: "水果", pinyin: "shuǐguǒ", meaning: "trái cây", category: "7", part: "1" },
  { chinese: "苹果", pinyin: "píngguǒ", meaning: "quả táo", category: "7", part: "1" },
  { chinese: "西瓜", pinyin: "xīguā", meaning: "dưa hấu", category: "7", part: "1" },
  { chinese: "芒果", pinyin: "mángguǒ", meaning: "xoài", category: "7", part: "1" },
  { chinese: "菠萝", pinyin: "bōluó", meaning: "dứa", category: "7", part: "1" },
  { chinese: "鸡蛋", pinyin: "jīdàn", meaning: "trứng gà", category: "7", part: "1" },
  { chinese: "面包", pinyin: "miànbāo", meaning: "bánh mì", category: "7", part: "1" },
  { chinese: "饼干", pinyin: "bǐnggān", meaning: "bánh quy", category: "7", part: "1" },
  { chinese: "茶", pinyin: "chá", meaning: "trà", category: "7", part: "1" },
  { chinese: "咖啡", pinyin: "kāfēi", meaning: "cà phê", category: "7", part: "1" },
  { chinese: "果汁", pinyin: "guǒzhī", meaning: "nước ép trái cây", category: "7", part: "1" },
  { chinese: "水", pinyin: "shuǐ", meaning: "nước", category: "7", part: "1" },
  { chinese: "牛奶", pinyin: "niúnǎi", meaning: "sữa bò", category: "7", part: "1" },
  { chinese: "啤酒", pinyin: "píjiǔ", meaning: "bia", category: "7", part: "1" },
  { chinese: "可乐", pinyin: "kělè", meaning: "coca", category: "7", part: "1" },
  { chinese: "蛋糕", pinyin: "dàngāo", meaning: "bánh gato", category: "7", part: "1" },
  { chinese: "菜", pinyin: "cài", meaning: "món ăn, rau", category: "7", part: "1" },
  { chinese: "菜单", pinyin: "càidān", meaning: "thực đơn", category: "7", part: "1" },
  { chinese: "午饭", pinyin: "wǔfàn", meaning: "bữa trưa", category: "7", part: "1" },
  { chinese: "蔬菜", pinyin: "shūcài", meaning: "rau củ", category: "7", part: "2" },
  { chinese: "鱼", pinyin: "yú", meaning: "cá", category: "7", part: "2" },
  { chinese: "牛肉", pinyin: "niúròu", meaning: "thịt bò", category: "7", part: "2" },
  { chinese: "鸡肉", pinyin: "jīròu", meaning: "thịt gà", category: "7", part: "2" },
  { chinese: "面条", pinyin: "miàntiáo", meaning: "mì sợi", category: "7", part: "2" },
  { chinese: "早饭", pinyin: "zǎofàn", meaning: "bữa sáng", category: "7", part: "2" },
  { chinese: "晚饭", pinyin: "wǎnfàn", meaning: "bữa tối", category: "7", part: "2" },
  { chinese: "饮料", pinyin: "yǐnliào", meaning: "đồ uống", category: "7", part: "3" },
  { chinese: "香蕉", pinyin: "xiāngjiāo", meaning: "chuối", category: "7", part: "3" },
  { chinese: "食物", pinyin: "shíwù", meaning: "thức ăn, thực phẩm", category: "7", part: "4" },
  { chinese: "饿", pinyin: "è", meaning: "đói", category: "7", part: "4" },
  { chinese: "渴", pinyin: "kě", meaning: "khát", category: "7", part: "4" },
  { chinese: "饱", pinyin: "bǎo", meaning: "no", category: "7", part: "4" },
  { chinese: "竹子", pinyin: "zhúzi", meaning: "cây tre, trúc", category: "7", part: "4" },

  // 8. Mua sắm & tiền bạc 
  { chinese: "钱", pinyin: "qián", meaning: "tiền", category: "8", part: "1" },
  { chinese: "块", pinyin: "kuài", meaning: "đồng (đơn vị tiền)", category: "8", part: "1" },
  { chinese: "多少", pinyin: "duōshao", meaning: "bao nhiêu", category: "8", part: "1" },
  { chinese: "发票", pinyin: "fāpiào", meaning: "hóa đơn", category: "8", part: "1" },
  { chinese: "便宜", pinyin: "piányi", meaning: "rẻ", category: "8", part: "2" },
  { chinese: "贵", pinyin: "guì", meaning: "đắt", category: "8", part: "2" },
  { chinese: "票", pinyin: "piào", meaning: "vé", category: "8", part: "2" },
  { chinese: "斤", pinyin: "jīn", meaning: "cân (500 gram)", category: "8", part: "3" },

  // 9. Đồ vật & địa điểm 
  { chinese: "家", pinyin: "jiā", meaning: "nhà, gia đình", category: "9", part: "1" },
  { chinese: "学校", pinyin: "xuéxiào", meaning: "trường học", category: "9", part: "1" },
  { chinese: "桌子", pinyin: "zhuōzi", meaning: "cái bàn", category: "9", part: "1" },
  { chinese: "椅子", pinyin: "yǐzi", meaning: "cái ghế", category: "9", part: "1" },
  { chinese: "杯子", pinyin: "bēizi", meaning: "cái cốc", category: "9", part: "1" },
  { chinese: "杯", pinyin: "bēi", meaning: "cốc, chén", category: "9", part: "1" },
  { chinese: "饭店", pinyin: "fàndiàn", meaning: "nhà hàng, khách sạn", category: "9", part: "1" },
  { chinese: "商店", pinyin: "shāngdiàn", meaning: "cửa hàng, tiệm", category: "9", part: "1" },
  { chinese: "前面", pinyin: "qiánmiàn", meaning: "phía trước", category: "9", part: "1" },
  { chinese: "医院", pinyin: "yīyuàn", meaning: "bệnh viện", category: "9", part: "1" },
  { chinese: "后面", pinyin: "hòumiàn", meaning: "phía sau", category: "9", part: "1" },
  { chinese: "电视", pinyin: "diànshì", meaning: "tivi", category: "9", part: "1" },
  { chinese: "机场", pinyin: "jīchǎng", meaning: "sân bay", category: "9", part: "1" },
  { chinese: "飞机", pinyin: "fēijī", meaning: "máy bay", category: "9", part: "1" },
  { chinese: "出租车", pinyin: "chūzūchē", meaning: "xe taxi", category: "9", part: "1" },
  { chinese: "酒店", pinyin: "jiǔdiàn", meaning: "khách sạn", category: "9", part: "1" },
  { chinese: "车", pinyin: "chē", meaning: "xe", category: "9", part: "1" },
  { chinese: "空调", pinyin: "kōngtiáo", meaning: "điều hòa", category: "9", part: "1" },
  { chinese: "大学", pinyin: "dàxué", meaning: "đại học", category: "9", part: "1" },
  { chinese: "电脑", pinyin: "diànnǎo", meaning: "máy tính", category: "9", part: "1" },
  { chinese: "旁边", pinyin: "pángbiān", meaning: "bên cạnh", category: "9", part: "1" },
  { chinese: "商场", pinyin: "shāngchǎng", meaning: "trung tâm thương mại", category: "9", part: "1" },
  { chinese: "左边", pinyin: "zuǒbiān", meaning: "bên trái", category: "9", part: "1" },
  { chinese: "右边", pinyin: "yòubiān", meaning: "bên phải", category: "9", part: "1" },
  { chinese: "铅笔", pinyin: "qiānbǐ", meaning: "bút chì", category: "9", part: "1" },
  { chinese: "路", pinyin: "lù", meaning: "đường", category: "9", part: "1" },
  { chinese: "门", pinyin: "mén", meaning: "cửa", category: "9", part: "1" },
  { chinese: "公共汽车", pinyin: "gōnggòng qìchē", meaning: "xe buýt", category: "9", part: "1" },
  { chinese: "地铁", pinyin: "dìtiě", meaning: "tàu điện ngầm", category: "9", part: "1" },
  { chinese: "公司", pinyin: "gōngsī", meaning: "công ty", category: "9", part: "1" },
  { chinese: "前", pinyin: "qián", meaning: "phía trước", category: "9", part: "2" },
  { chinese: "近", pinyin: "jìn", meaning: "gần", category: "9", part: "2" },
  { chinese: "线", pinyin: "xiàn", meaning: "tuyến (xe buýt), đường", category: "9", part: "2" },
  { chinese: "上面", pinyin: "shàngmiàn", meaning: "bên trên", category: "9", part: "2" },
  { chinese: "这边", pinyin: "zhèbiān", meaning: "bên này", category: "9", part: "2" },
  { chinese: "裙子", pinyin: "qúnzi", meaning: "váy", category: "9", part: "2" },
  { chinese: "房间", pinyin: "fángjiān", meaning: "phòng", category: "9", part: "2" },
  { chinese: "火车站", pinyin: "huǒchēzhàn", meaning: "ga tàu lửa", category: "9", part: "2" },
  { chinese: "眼睛", pinyin: "yǎnjīng", meaning: "mắt", category: "9", part: "2" },
  { chinese: "宾馆", pinyin: "bīnguǎn", meaning: "khách sạn", category: "9", part: "2" },
  { chinese: "地方", pinyin: "dìfang", meaning: "nơi, chỗ", category: "9", part: "2" },
  { chinese: "外", pinyin: "wài", meaning: "ngoài", category: "9", part: "2" },
  { chinese: "教室", pinyin: "jiàoshì", meaning: "phòng học", category: "9", part: "2" },
  { chinese: "手机", pinyin: "shǒujī", meaning: "điện thoại di động", category: "9", part: "2" },
  { chinese: "手表", pinyin: "shǒubiǎo", meaning: "đồng hồ đeo tay", category: "9", part: "2" },
  { chinese: "身体", pinyin: "shēntǐ", meaning: "cơ thể, sức khỏe", category: "9", part: "2" },
  { chinese: "雪", pinyin: "xuě", meaning: "tuyết", category: "9", part: "2" },
  { chinese: "报纸", pinyin: "bàozhǐ", meaning: "báo chí", category: "9", part: "2" },
  { chinese: "公斤", pinyin: "gōngjīn", meaning: "kilogram (kg)", category: "9", part: "3" },
  { chinese: "中间", pinyin: "zhōngjiān", meaning: "ở giữa", category: "9", part: "3" },
  { chinese: "电话", pinyin: "diànhuà", meaning: "điện thoại (cố định)", category: "9", part: "3" },
  { chinese: "床", pinyin: "chuáng", meaning: "cái giường", category: "9", part: "3" },
  { chinese: "笔记本", pinyin: "bǐjìběn", meaning: "sổ tay, laptop", category: "9", part: "3" },
  { chinese: "地图", pinyin: "dìtú", meaning: "bản đồ", category: "9", part: "3" },
  { chinese: "世界", pinyin: "shìjiè", meaning: "thế giới", category: "9", part: "3" },
  { chinese: "楼", pinyin: "lóu", meaning: "lầu, tầng, tòa nhà", category: "9", part: "3" },
  { chinese: "护照", pinyin: "hùzhào", meaning: "hộ chiếu", category: "9", part: "3" },
  { chinese: "包", pinyin: "bāo", meaning: "cái túi, gói", category: "9", part: "3" },
  { chinese: "行李箱", pinyin: "xínglǐxiāng", meaning: "vali", category: "9", part: "3" },
  { chinese: "公园", pinyin: "gōngyuán", meaning: "công viên", category: "9", part: "3" },
  { chinese: "照片", pinyin: "zhàopiàn", meaning: "ảnh, tấm hình", category: "9", part: "3" },
  { chinese: "礼物", pinyin: "lǐwù", meaning: "quà tặng", category: "9", part: "3" },
  { chinese: "脸", pinyin: "liǎn", meaning: "mặt, khuôn mặt", category: "9", part: "3" },
  { chinese: "体育", pinyin: "tǐyù", meaning: "thể dục, thể thao", category: "9", part: "3" },
  { chinese: "附近", pinyin: "fùjìn", meaning: "gần đây, lân cận", category: "9", part: "3" },
  { chinese: "环境", pinyin: "huánjìng", meaning: "môi trường", category: "9", part: "3" },
  { chinese: "伞", pinyin: "sǎn", meaning: "cái ô, cái dù", category: "9", part: "3" },
  { chinese: "口", pinyin: "kǒu", meaning: "miệng, cổng(menkou: cổng,chukou: lối ra)", category: "9", part: "3" },
  { chinese: "外面", pinyin: "wàimiàn", meaning: "bên ngoài", category: "9", part: "3" },
  { chinese: "办公室", pinyin: "bàngōngshì", meaning: "văn phòng", category: "9", part: "3" },
  { chinese: "头发", pinyin: "tóufa", meaning: "tóc", category: "9", part: "3" },
  { chinese: "双", pinyin: "shuāng", meaning: "đôi, chiếc (lượng từ)", category: "9", part: "3" },
  { chinese: "皮鞋", pinyin: "píxié", meaning: "giày da", category: "9", part: "3" },
  { chinese: "鞋", pinyin: "xié", meaning: "giày", category: "9", part: "3" },
  { chinese: "衣柜", pinyin: "yīguì", meaning: "tủ quần áo", category: "9", part: "3" },
  { chinese: "房子", pinyin: "fángzi", meaning: "nhà, căn hộ", category: "9", part: "3" },
  { chinese: "会议", pinyin: "huìyì", meaning: "cuộc họp", category: "9", part: "3" },
  { chinese: "衬衫", pinyin: "chènshān", meaning: "áo sơ mi", category: "9", part: "3" },
  { chinese: "冰箱", pinyin: "bīngxiāng", meaning: "tủ lạnh", category: "9", part: "3" },
  { chinese: "超市", pinyin: "chāoshì", meaning: "siêu thị", category: "9", part: "3" },
  { chinese: "筷子", pinyin: "kuàizi", meaning: "đũa", category: "9", part: "3" },
  { chinese: "盘子", pinyin: "pánzi", meaning: "cái đĩa, mâm", category: "9", part: "3" },
  { chinese: "碗", pinyin: "wǎn", meaning: "cái bát, chén", category: "9", part: "3" },
  { chinese: "音乐", pinyin: "yīnyuè", meaning: "âm nhạc", category: "9", part: "3" },
  { chinese: "船", pinyin: "chuán", meaning: "thuyền, tàu", category: "9", part: "3" },
  { chinese: "岛", pinyin: "dǎo", meaning: "hòn đảo", category: "9", part: "3" },
  { chinese: "月亮", pinyin: "yuèliang", meaning: "mặt trăng", category: "9", part: "3" },
  { chinese: "游戏", pinyin: "yóuxì", meaning: "trò chơi", category: "9", part: "3" },
  { chinese: "鼻子", pinyin: "bízi", meaning: "mũi", category: "9", part: "4" },
  { chinese: "嘴", pinyin: "zuǐ", meaning: "miệng", category: "9", part: "4" },
  { chinese: "北方", pinyin: "běifāng", meaning: "phía bắc", category: "9", part: "4" },
  { chinese: "东", pinyin: "dōng", meaning: "phía đông", category: "9", part: "4" },
  { chinese: "南", pinyin: "nán", meaning: "phía nam", category: "9", part: "4" },
  { chinese: "西", pinyin: "xī", meaning: "phía tây", category: "9", part: "4" },
  { chinese: "河", pinyin: "hé", meaning: "sông", category: "9", part: "4" },
  { chinese: "银行", pinyin: "yínháng", meaning: "ngân hàng", category: "9", part: "4" },
  { chinese: "电影院", pinyin: "diànyǐngyuàn", meaning: "rạp chiếu phim", category: "9", part: "4" },
  { chinese: "电梯", pinyin: "diàntī", meaning: "thang máy", category: "9", part: "4" },
  { chinese: "腿", pinyin: "tuǐ", meaning: "chân", category: "9", part: "4" },
  { chinese: "鸟", pinyin: "niǎo", meaning: "chim", category: "9", part: "4" },
  { chinese: "动物", pinyin: "dòngwù", meaning: "động vật", category: "9", part: "4" },
  { chinese: "熊猫", pinyin: "xióngmāo", meaning: "gấu trúc", category: "9", part: "4" },
  { chinese: "熊", pinyin: "xióng", meaning: "gấu", category: "9", part: "4" },
  { chinese: "马", pinyin: "mǎ", meaning: "ngựa", category: "9", part: "4" },

  // 10. Từ khác
  { chinese: "好", pinyin: "hǎo", meaning: "tốt, khỏe", category: "10", part: "1" },
  { chinese: "名字", pinyin: "míngzi", meaning: "tên", category: "10", part: "1" },
  { chinese: "哪", pinyin: "nǎ", meaning: "nào, ở đâu", category: "10", part: "1" },
  { chinese: "谁", pinyin: "shéi", meaning: "ai", category: "10", part: "1" },
  { chinese: "再见", pinyin: "zàijiàn", meaning: "tạm biệt", category: "10", part: "1" },
  { chinese: "吗", pinyin: "ma", meaning: "không? (trợ từ nghi vấn)", category: "10", part: "1" },
  { chinese: "都", pinyin: "dōu", meaning: "đều, tất cả", category: "10", part: "1" },
  { chinese: "里", pinyin: "lǐ", meaning: "trong, ở trong", category: "10", part: "1" },
  { chinese: "也", pinyin: "yě", meaning: "cũng", category: "10", part: "1" },
  { chinese: "和", pinyin: "hé", meaning: "và", category: "10", part: "1" },
  { chinese: "这", pinyin: "zhè", meaning: "đây, cái này", category: "10", part: "1" },
  { chinese: "那", pinyin: "nà", meaning: "kia, cái kia", category: "10", part: "1" },
  { chinese: "大", pinyin: "dà", meaning: "to, lớn", category: "10", part: "1" },
  { chinese: "小", pinyin: "xiǎo", meaning: "nhỏ", category: "10", part: "1" },
  { chinese: "什么", pinyin: "shénme", meaning: "gì, cái gì", category: "10", part: "1" },
  { chinese: "几", pinyin: "jǐ", meaning: "mấy", category: "10", part: "1" },
  { chinese: "呢", pinyin: "ne", meaning: "nhỉ, nhé (trợ từ)", category: "10", part: "1" },
  { chinese: "对不起", pinyin: "duìbùqǐ", meaning: "xin lỗi", category: "10", part: "1" },
  { chinese: "没关系", pinyin: "méiguānxi", meaning: "không sao", category: "10", part: "1" },
  { chinese: "谢谢", pinyin: "xièxie", meaning: "cảm ơn", category: "10", part: "1" },
  { chinese: "不客气", pinyin: "búkèqi", meaning: "không có gì, đừng khách sáo", category: "10", part: "1" },
  { chinese: "个", pinyin: "ge", meaning: "cái, chiếc (lượng từ)", category: "10", part: "1" },
  { chinese: "号", pinyin: "hào", meaning: "số, ngày", category: "10", part: "1" },
  { chinese: "了", pinyin: "le", meaning: "rồi (trợ từ)", category: "10", part: "1" },
  { chinese: "在", pinyin: "zài", meaning: "ở, đang", category: "10", part: "1" },
  { chinese: "晚上好", pinyin: "wǎnshàng hǎo", meaning: "chào buổi tối", category: "10", part: "1" },
  { chinese: "好的", pinyin: "hǎode", meaning: "được, vâng (đồng ý)", category: "10", part: "1" },
  { chinese: "辛苦了", pinyin: "xīnkǔle", meaning: "vất vả rồi", category: "10", part: "1" },
  { chinese: "一点儿", pinyin: "yìdiǎnr", meaning: "một chút", category: "10", part: "1" },
  { chinese: "上", pinyin: "shàng", meaning: "trên", category: "10", part: "1" },
  { chinese: "很", pinyin: "hěn", meaning: "rất", category: "10", part: "1" },
  { chinese: "猫", pinyin: "māo", meaning: "mèo", category: "10", part: "1" },
  { chinese: "狗", pinyin: "gǒu", meaning: "chó", category: "10", part: "1" },
  { chinese: "下", pinyin: "xià", meaning: "dưới, xuống", category: "10", part: "1" },
  { chinese: "漂亮", pinyin: "piàoliang", meaning: "đẹp", category: "10", part: "1" },
  { chinese: "多", pinyin: "duō", meaning: "nhiều", category: "10", part: "1" },
  { chinese: "高兴", pinyin: "gāoxìng", meaning: "vui vẻ, vui mừng", category: "10", part: "1" },
  { chinese: "东西", pinyin: "dōngxi", meaning: "đồ vật, thứ", category: "10", part: "1" },
  { chinese: "衣服", pinyin: "yīfu", meaning: "quần áo", category: "10", part: "1" },
  { chinese: "哪儿", pinyin: "nǎr", meaning: "ở đâu", category: "10", part: "1" },
  { chinese: "些", pinyin: "xiē", meaning: "một vài, một số", category: "10", part: "1" },
  { chinese: "喂", pinyin: "wéi", meaning: "alo, này", category: "10", part: "1" },
  { chinese: "感冒", pinyin: "gǎnmào", meaning: "cảm cúm", category: "10", part: "1" },
  { chinese: "怎么", pinyin: "zěnme", meaning: "như thế nào, làm sao", category: "10", part: "1" },
  { chinese: "少", pinyin: "shǎo", meaning: "ít, thiếu", category: "10", part: "1" },
  { chinese: "天气", pinyin: "tiānqì", meaning: "thời tiết", category: "10", part: "1" },
  { chinese: "冷", pinyin: "lěng", meaning: "lạnh", category: "10", part: "1" },
  { chinese: "热", pinyin: "rè", meaning: "nóng", category: "10", part: "1" },
  { chinese: "下雨", pinyin: "xiàyǔ", meaning: "trời mưa", category: "10", part: "1" },
  { chinese: "怎么样", pinyin: "zěnmeyàng", meaning: "thế nào", category: "10", part: "1" },
  { chinese: "有点儿", pinyin: "yǒudiǎnr", meaning: "hơi, có chút", category: "10", part: "1" },
  { chinese: "本", pinyin: "běn", meaning: "quyển (lượng từ)", category: "10", part: "1" },
  { chinese: "考试", pinyin: "kǎoshì", meaning: "thi cử, bài kiểm tra", category: "10", part: "1" },
  { chinese: "姓", pinyin: "xìng", meaning: "họ", category: "10", part: "1" },
  { chinese: "一下", pinyin: "yīxià", meaning: "một chút, một lát", category: "10", part: "1" },
  { chinese: "新", pinyin: "xīn", meaning: "mới", category: "10", part: "1" },
  { chinese: "已经", pinyin: "yǐjīng", meaning: "đã, rồi", category: "10", part: "1" },
  { chinese: "吧", pinyin: "ba", meaning: "nhỉ, nhé (trợ từ)", category: "10", part: "1" },
  { chinese: "还", pinyin: "hái", meaning: "vẫn, còn", category: "10", part: "1" },
  { chinese: "短", pinyin: "duǎn", meaning: "ngắn", category: "10", part: "1" },
  { chinese: "高", pinyin: "gāo", meaning: "cao", category: "10", part: "1" },
  { chinese: "矮", pinyin: "ǎi", meaning: "thấp", category: "10", part: "1" },
  { chinese: "非常", pinyin: "fēicháng", meaning: "vô cùng, rất", category: "10", part: "1" },
  { chinese: "快", pinyin: "kuài", meaning: "nhanh", category: "10", part: "1" },
  { chinese: "远", pinyin: "yuǎn", meaning: "xa", category: "10", part: "1" },
  { chinese: "每", pinyin: "měi", meaning: "mỗi, mọi", category: "10", part: "1" },
  { chinese: "题", pinyin: "tí", meaning: "câu hỏi, đề", category: "10", part: "2" },
  { chinese: "作业", pinyin: "zuòyè", meaning: "bài tập về nhà", category: "10", part: "2" },
  { chinese: "件", pinyin: "jiàn", meaning: "chiếc (lượng từ)", category: "10", part: "2" },
  { chinese: "正在", pinyin: "zhèngzài", meaning: "đang", category: "10", part: "2" },
  { chinese: "最", pinyin: "zuì", meaning: "nhất (phó từ)", category: "10", part: "2" },
  { chinese: "再", pinyin: "zài", meaning: "thêm, lần nữa", category: "10", part: "2" },
  { chinese: "比", pinyin: "bǐ", meaning: "so sánh", category: "10", part: "2" },
  { chinese: "啊", pinyin: "a", meaning: "trợ từ ngữ khí", category: "10", part: "2" },
  { chinese: "好看", pinyin: "hǎokàn", meaning: "đẹp, dễ nhìn", category: "10", part: "2" },
  { chinese: "颜色", pinyin: "yánsè", meaning: "màu sắc", category: "10", part: "2" },
  { chinese: "累", pinyin: "lèi", meaning: "mệt", category: "10", part: "2" },
  { chinese: "真", pinyin: "zhēn", meaning: "thật, thực sự", category: "10", part: "2" },
  { chinese: "红", pinyin: "hóng", meaning: "màu đỏ", category: "10", part: "2" },
  { chinese: "生病", pinyin: "shēngbìng", meaning: "ốm, bệnh", category: "10", part: "2" },
  { chinese: "药", pinyin: "yào", meaning: "thuốc", category: "10", part: "2" },
  { chinese: "为什么", pinyin: "wèishénme", meaning: "tại sao", category: "10", part: "2" },
  { chinese: "问题", pinyin: "wèntí", meaning: "vấn đề, câu hỏi", category: "10", part: "2" },
  { chinese: "虽然", pinyin: "suīrán", meaning: "mặc dù", category: "10", part: "2" },
  { chinese: "但是", pinyin: "dànshì", meaning: "nhưng", category: "10", part: "2" },
  { chinese: "不错", pinyin: "búcuò", meaning: "không tồi, tốt", category: "10", part: "2" },
  { chinese: "别", pinyin: "bié", meaning: "đừng", category: "10", part: "2" },
  { chinese: "张", pinyin: "zhāng", meaning: "tấm, tờ (lượng từ)", category: "10", part: "2" },
  { chinese: "事情", pinyin: "shìqing", meaning: "sự việc", category: "10", part: "2" },
  { chinese: "忙", pinyin: "máng", meaning: "bận", category: "10", part: "2" },
  { chinese: "得", pinyin: "de", meaning: "Trợ từ ngữ pháp", category: "10", part: "2" },
  { chinese: "白色", pinyin: "báisè", meaning: "màu trắng", category: "10", part: "2" },
  { chinese: "红色", pinyin: "hóngsè", meaning: "màu đỏ", category: "10", part: "2" },
  { chinese: "黑色", pinyin: "hēisè", meaning: "màu đen", category: "10", part: "2" },
  { chinese: "早", pinyin: "zǎo", meaning: "sớm", category: "10", part: "2" },
  { chinese: "瘦", pinyin: "shòu", meaning: "gầy", category: "10", part: "3" },
  { chinese: "胖", pinyin: "pàng", meaning: "béo", category: "10", part: "3" },
  { chinese: "米", pinyin: "mǐ", meaning: "mét (m)", category: "10", part: "3" },
  { chinese: "第一", pinyin: "dì yī", meaning: "thứ nhất, số một", category: "10", part: "2" },
  { chinese: "好玩", pinyin: "hǎowán", meaning: "vui, thú vị", category: "10", part: "2" },
  { chinese: "因为", pinyin: "yīnwèi", meaning: "vì, bởi vì", category: "10", part: "2" },
  { chinese: "所以", pinyin: "suǒyǐ", meaning: "cho nên", category: "10", part: "2" },
  { chinese: "白", pinyin: "bái", meaning: "màu trắng", category: "10", part: "2" },
  { chinese: "黑", pinyin: "hēi", meaning: "màu đen", category: "10", part: "2" },
  { chinese: "着", pinyin: "zhe", meaning: "đang (trợ từ động thái)", category: "10", part: "2" },
  { chinese: "它", pinyin: "tā", meaning: "nó (động vật, đồ vật)", category: "10", part: "2" },
  { chinese: "慢", pinyin: "màn", meaning: "chậm", category: "10", part: "2" },
  { chinese: "错", pinyin: "cuò", meaning: "sai", category: "10", part: "2" },
  { chinese: "晴", pinyin: "qíng", meaning: "trời nắng", category: "10", part: "2" },
  { chinese: "阴", pinyin: "yīn", meaning: "trời râm, âm u", category: "10", part: "2" },
  { chinese: "可能", pinyin: "kěnéng", meaning: "có thể", category: "10", part: "2" },
  { chinese: "快乐", pinyin: "kuàilè", meaning: "vui vẻ, hạnh phúc", category: "10", part: "2" },
  { chinese: "个子", pinyin: "gèzi", meaning: "vóc dáng, chiều cao", category: "10", part: "3" },
  { chinese: "更", pinyin: "gèng", meaning: "hơn, càng", category: "10", part: "3" },
  { chinese: "难", pinyin: "nán", meaning: "khó", category: "10", part: "3" },
  { chinese: "担心", pinyin: "dānxīn", meaning: "lo lắng", category: "10", part: "3" },
  { chinese: "久", pinyin: "jiǔ", meaning: "lâu", category: "10", part: "3" },
  { chinese: "先", pinyin: "xiān", meaning: "trước", category: "10", part: "3" },
  { chinese: "然后", pinyin: "ránhòu", meaning: "sau đó", category: "10", part: "3" },
  { chinese: "特别", pinyin: "tèbié", meaning: "đặc biệt", category: "10", part: "3" },
  { chinese: "甜", pinyin: "tián", meaning: "ngọt", category: "10", part: "3" },
  { chinese: "跟", pinyin: "gēn", meaning: "với, cùng", category: "10", part: "3" },
  { chinese: "一样", pinyin: "yīyàng", meaning: "giống nhau", category: "10", part: "3" },
  { chinese: "聪明", pinyin: "cōngming", meaning: "thông minh", category: "10", part: "3" },
  { chinese: "努力", pinyin: "nǔlì", meaning: "cố gắng, nỗ lực", category: "10", part: "3" },
  { chinese: "热情", pinyin: "rèqíng", meaning: "nhiệt tình, nhiệt huyết", category: "10", part: "3" },
  { chinese: "样子", pinyin: "yàngzi", meaning: "vẻ ngoài, dáng vẻ", category: "10", part: "3" },
  { chinese: "要求", pinyin: "yāoqiú", meaning: "yêu cầu", category: "10", part: "3" },
  { chinese: "花", pinyin: "huā", meaning: "tiêu (tiền), hoa", category: "10", part: "3" },
  { chinese: "安静", pinyin: "ānjìng", meaning: "yên tĩnh", category: "10", part: "3" },
  { chinese: "才", pinyin: "cái", meaning: "mới (phó từ)", category: "10", part: "3" },
  { chinese: "突然", pinyin: "tūrán", meaning: "đột nhiên", category: "10", part: "3" },
  { chinese: "总是", pinyin: "zǒngshì", meaning: "luôn luôn", category: "10", part: "3" },
  { chinese: "舒服", pinyin: "shūfu", meaning: "thoải mái, dễ chịu", category: "10", part: "3" },
  { chinese: "脸色", pinyin: "liǎnsè", meaning: "sắc mặt", category: "10", part: "3" },
  { chinese: "最后", pinyin: "zuìhòu", meaning: "cuối cùng", category: "10", part: "3" },
  { chinese: "马上", pinyin: "mǎshàng", meaning: "ngay lập tức", category: "10", part: "3" },
  { chinese: "还是", pinyin: "háishi", meaning: "hay là, vẫn", category: "10", part: "3" },
  { chinese: "旧", pinyin: "jiù", meaning: "cũ", category: "10", part: "3" },
  { chinese: "容易", pinyin: "róngyì", meaning: "dễ dàng", category: "10", part: "3" },
  { chinese: "变化", pinyin: "biànhuà", meaning: "thay đổi, biến hóa", category: "10", part: "3" },
  { chinese: "又", pinyin: "yòu", meaning: "lại (lặp lại hành động)", category: "10", part: "3" },
  { chinese: "重要", pinyin: "zhòngyào", meaning: "quan trọng", category: "10", part: "3" },
  { chinese: "条", pinyin: "tiáo", meaning: "chiếc (lượng từ cho vật dài)", category: "10", part: "3" },
  { chinese: "裤子", pinyin: "kùzi", meaning: "quần", category: "10", part: "3" },
  { chinese: "其他", pinyin: "qítā", meaning: "khác, cái khác", category: "10", part: "3" },
  { chinese: "绿色", pinyin: "lǜsè", meaning: "màu xanh lá", category: "10", part: "3" },
  { chinese: "蓝色", pinyin: "lánsè", "meaning": "màu xanh dương", category: "10", part: "3" },
  { chinese: "光临", pinyin: "guānglín", meaning: "quang lâm (kính ngữ)", category: "10", part: "3" },
  { chinese: "位", pinyin: "wèi", meaning: "vị (lượng từ kính ngữ)", category: "10", part: "3" },
  { chinese: "安全", pinyin: "ānquán", meaning: "an toàn", category: "10", part: "3" },
  { chinese: "危险", pinyin: "wēixiǎn", meaning: "nguy hiểm", category: "10", part: "3" },
  { chinese: "一边", pinyin: "yìbiān", meaning: "vừa...vừa...", category: "10", part: "3" },
  { chinese: "差", pinyin: "chà", meaning: "kém, tồi, thiếu", category: "10", part: "3" },
  { chinese: "如果", pinyin: "rúguǒ", meaning: "nếu như", category: "10", part: "3" },
  { chinese: "就", pinyin: "jiù", meaning: "thì, liền", category: "10", part: "3" },
  { chinese: "只", pinyin: "zhǐ/zhi", meaning: "chỉ,con (lượng từ cho động vật)", category: "10", part: "4" },
  { chinese: "新鲜", pinyin: "xīnxiān", meaning: "tươi, mới", category: "10", part: "3" },
  { chinese: "经常", pinyin: "jīngcháng", meaning: "thường xuyên", category: "10", part: "3" },
  { chinese: "刮风", pinyin: "guāfēng", meaning: "gió thổi", category: "10", part: "3" },
  { chinese: "爱好", pinyin: "àihào", meaning: "sở thích", category: "10", part: "3" },
  { chinese: "水平", pinyin: "shuǐpíng", meaning: "trình độ, mức độ", category: "10", part: "3" },
  { chinese: "不但...而且", pinyin: "búdàn... érqiě", meaning: "không những... mà còn...", category: "10", part: "3" },
  { chinese: "为了", pinyin: "wèile", meaning: "vì, để", category: "10", part: "3" },
  { chinese: "长", pinyin: "cháng/zhǎng", meaning: "dài,lớn lên, trưởng thành", category: "10", part: "4" },
  { chinese: "像", pinyin: "xiàng", meaning: "giống, như là", category: "10", part: "4" },
  { chinese: "发", pinyin: "fà", meaning: "Phát ra, phóng ra, gửi đi", category: "10", part: "4" },
  { chinese: "有名", pinyin: "yǒumíng", meaning: "nổi tiếng", category: "10", part: "4" },
  { chinese: "比赛", pinyin: "bǐsài", meaning: "cuộc thi đấu, trận đấu, cuộc đua", category: "10", part: "4" },
  { chinese: "成绩", pinyin: "chéngjì", meaning: "thành tích, kết quả", category: "10", part: "4" },
  { chinese: "马拉松", pinyin: "mǎlāsōng", meaning: "marathon", category: "10", part: "4" },
  { chinese: "越来越", pinyin: "yuè lái yuè", meaning: "càng ngày càng", category: "10", part: "4" },
  { chinese: "比较", pinyin: "bǐjiào", meaning: "tương đối, khá", category: "10", part: "4" },
  { chinese: "方便", pinyin: "fāngbiàn", meaning: "thuận tiện, tiện lợi,", category: "10", part: "4" },
  { chinese: "老", pinyin: "lǎo", meaning: "cũ, già", category: "10", part: "4" },
  { chinese: "当然", pinyin: "dāngrán", meaning: "đương nhiên", category: "10", part: "4" },
  { chinese: "极了", pinyin: "jíle", meaning: "vô cùng, cực kỳ", category: "10", part: "4" },
  { chinese: "不是...吗", pinyin: "bú shì... ma", meaning: "không phải... sao?", category: "10", part: "4" },
  { chinese: "办法", pinyin: "bànfǎ", meaning: "biện pháp, cách làm", category: "10", part: "4" },
  { chinese: "可爱", pinyin: "kě'ài", meaning: "dễ thương", category: "10", part: "4" },
  { chinese: "害怕", pinyin: "hàipà", meaning: "sợ hãi", category: "10", part: "4" },
];
const vocabularyDataSimple = [
  { chinese: "你", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "我", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "她", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "他", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "们", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "您", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "是", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "的", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "叫", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "不", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "说", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "会", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "学", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "写", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "吃", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "喜", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "欢", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "喝", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "想", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "买", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "有", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "没", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "做", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "去", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "回", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "来", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "看", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "见", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "要", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "住", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "工", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "作", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "认", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "识", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "坐", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "请", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "到", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "睡", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "觉", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "开", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "问", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "读", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "爱", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "听", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "打", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "电", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "话", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "介", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "绍", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "可", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "乐", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "等", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "学", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "生", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "工", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "程", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "师", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "老", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "爸", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "妈", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "朋", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "友", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "同", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "人", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "员", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "职", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "先", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "女", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "儿", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "医", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "孩", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "姐", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "中", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "国", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "美", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "越", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "南", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "汉", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "语", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "文", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "英", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "字", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "零", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "百", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "今", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "天", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "昨", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "明", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "上", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "午", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "下", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "月", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "年", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "岁", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "日", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "现", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "在", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "点", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "分", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "钟", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "时", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "候", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "间", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "多", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "久", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "小", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "饭", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "苹", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "果", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "西", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "瓜", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "芒", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "菠", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "萝", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "鸡", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "蛋", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "面", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "包", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "饼", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "干", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "茶", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "咖", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "啡", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "汁", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "水", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "牛", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "奶", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "啤", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "酒", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "可", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "乐", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "蛋", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "糕", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "菜", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "单", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "钱", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "块", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "少", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "发", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "票", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "家", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "校", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "卓", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "子", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "椅", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "杯", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "店", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "商", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "前", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "面", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "院", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "电", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "视", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "脑", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "机", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "场", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "飞", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "出", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "车", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "租", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "空", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "调", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "大", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "旁", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "边", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "左", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "右", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "铅", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "笔", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "路", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "门", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "公", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "供", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "气", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "地", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "铁", pinyin: "", meaning: "", category: "1", part: "1" },
  { chinese: "地", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "铁", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "司", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "好", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "名", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "字", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "哪", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "谁", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "再", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "吗", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "都", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "里", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "也", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "和", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "这", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "那", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "大", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "什", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "么", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "几", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "呢", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "对", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "起", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "关", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "系", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "谢", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "客", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "个", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "以", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "号", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "了", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "晚", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "辛", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "苦", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "很", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "猫", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "狗", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "漂", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "亮", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "高", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "兴", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "东", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "衣", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "服", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "些", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "喂", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "感", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "冒", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "怎", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "冷", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "热", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "雨", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "样", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "本", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "考", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "试", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "姓", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "新", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "已", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "经", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "吧", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "还", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "短", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "高", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "矮", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "非", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "常", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "长", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "快", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "远", pinyin: "", meaning: "", category: "1", part: "2" },
  { chinese: "每", pinyin: "", meaning: "", category: "1", part: "2" },
];

// Tên danh mục
const categoryNames = {
  "1": "Đại từ & nhân xưng",
  "2": "Động từ & trợ động từ",
  "3": "Nghề nghiệp & quan hệ",
  "4": "Quốc gia & dân tộc",
  "5": "Ngôn ngữ & chữ viết",
  "6": "Thời gian & số đếm",
  "7": "Thức ăn & đồ uống",
  "8": "Mua sắm & tiền bạc",
  "9": "Đồ vật & địa điểm",
  "10": "Từ khác"
};





